In [2]:
import pandas as pd 
df= pd.read_csv("E0.csv")
print(f"🚀 Dimensión del Dataset: {df.shape[0]} partidos y {df.shape[1]} variables distintas.")
columnas_clave = ['Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'B365H', 'B365D', 'B365A']
df_filtrado = df[columnas_clave]
df_filtrado

🚀 Dimensión del Dataset: 380 partidos y 106 variables distintas.

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,B365H,B365D,B365A
0,11/08/2023,Burnley,Man City,0,3,A,8.00,5.50,1.33
1,12/08/2023,Arsenal,Nott'm Forest,2,1,H,1.18,7.00,15.00
2,12/08/2023,Bournemouth,West Ham,1,1,D,2.70,3.40,2.55
3,12/08/2023,Brighton,Luton,4,1,H,1.33,5.50,9.00
4,12/08/2023,Everton,Fulham,0,1,A,2.20,3.40,3.30
...,...,...,...,...,...,...,...,...,...
375,19/05/2024,Crystal Palace,Aston Villa,5,0,H,1.85,4.33,3.60
376,19/05/2024,Liverpool,Wolves,2,0,H,1.17,8.00,15.00
377,19/05/2024,Luton,Fulham,2,4,A,2.90,3.90,2.20
378,19/05/2024,Man City,West Ham,3,1,H,1.08,12.00,21.00
379,19/05/2024,Sheffield United,Tottenham,0,3,A,7.00,6.00,1.33

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 380 entries, 0 to 379
Columns: 106 entries, Div to AvgCAHA
dtypes: float64(82), int64(16), str(8)
memory usage: 314.8 KB

In [6]:
# hacemos el codigo legible 
traduccion = {'Date': 'Fecha',
    'HomeTeam': 'Equipo_Local',
    'AwayTeam': 'Equipo_Visitante',
    'FTHG': 'Goles_Local (FTHG)',
    'FTAG': 'Goles_Visitante (FTAG)',
    'FTR': 'Resultado_Final (FTR)',
    'B365H': 'Cuota_Local (B365H)',
    'B365D': 'Cuota_Empate (B365D)',
    'B365A': 'Cuota_Visitante (B365A)'
}
df_final = df_filtrado.rename(columns=traduccion)
print("columnas renombradas con exito")
df_final

columnas renombradas con exito

,Fecha,Equipo_Local,Equipo_Visitante,Goles_Local (FTHG),Goles_Visitante (FTAG),Resultado_Final (FTR),Cuota_Local (B365H),Cuota_Empate (B365D),Cuota_Visitante (B365A)
0,11/08/2023,Burnley,Man City,0,3,A,8.00,5.50,1.33
1,12/08/2023,Arsenal,Nott'm Forest,2,1,H,1.18,7.00,15.00
2,12/08/2023,Bournemouth,West Ham,1,1,D,2.70,3.40,2.55
3,12/08/2023,Brighton,Luton,4,1,H,1.33,5.50,9.00
4,12/08/2023,Everton,Fulham,0,1,A,2.20,3.40,3.30
...,...,...,...,...,...,...,...,...,...
375,19/05/2024,Crystal Palace,Aston Villa,5,0,H,1.85,4.33,3.60
376,19/05/2024,Liverpool,Wolves,2,0,H,1.17,8.00,15.00
377,19/05/2024,Luton,Fulham,2,4,A,2.90,3.90,2.20
378,19/05/2024,Man City,West Ham,3,1,H,1.08,12.00,21.00
379,19/05/2024,Sheffield United,Tottenham,0,3,A,7.00,6.00,1.33

In [7]:
df_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 380 entries, 0 to 379
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Fecha                    380 non-null    str
 1   Equipo_Local             380 non-null    str
 2   Equipo_Visitante         380 non-null    str
 3   Goles_Local (FTHG)       380 non-null    int64
 4   Goles_Visitante (FTAG)   380 non-null    int64
 5   Resultado_Final (FTR)    380 non-null    str
 6   Cuota_Local (B365H)      380 non-null    float64
 7   Cuota_Empate (B365D)     380 non-null    float64
 8   Cuota_Visitante (B365A)  380 non-null    float64
dtypes: float64(3), int64(2), str(4)
memory usage: 26.8 KB

In [10]:
df_final ["Fecha"] = pd.to_datetime(df_final["Fecha"],format="%d/%m/%Y")

In [11]:
df_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 380 entries, 0 to 379
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Fecha                    380 non-null    datetime64[us]
 1   Equipo_Local             380 non-null    str
 2   Equipo_Visitante         380 non-null    str
 3   Goles_Local (FTHG)       380 non-null    int64
 4   Goles_Visitante (FTAG)   380 non-null    int64
 5   Resultado_Final (FTR)    380 non-null    str
 6   Cuota_Local (B365H)      380 non-null    float64
 7   Cuota_Empate (B365D)     380 non-null    float64
 8   Cuota_Visitante (B365A)  380 non-null    float64
dtypes: datetime64[us](1), float64(3), int64(2), str(3)
memory usage: 26.8 KB

In [12]:
pip install sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.49-cp312-cp312-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.3.2-cp312-cp312-win_amd64.whl.metadata (3.8 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\angel\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from sqlalchemy) (4.15.0)
Downloading sqlalchemy-2.0.49-cp312-cp312-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 2.1/2.1 MB 20.0 MB/s eta 0:00:00
Downloading greenlet-3.3.2-cp312-cp312-win_amd64.whl (231 kB)
Installing collected packages: greenlet, sqlalchemy
Successfully installed greenlet-3.3.2 sqlalchemy-2.0.49
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: C:\Users\angel\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [14]:
import pyodbc
print(pyodbc.drivers())

['SQL Server', 'SQL Server Native Client RDA 11.0', 'ODBC Driver 17 for SQL Server', 'Microsoft Access Driver (*.mdb, *.accdb)', 'Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)', 'Microsoft Access Text Driver (*.txt, *.csv)']

In [15]:
parametros = urllib.parse.quote_plus(f"DRIVER={{SQL Server}};SERVER={server};DATABASE={database};Trusted_Connection=yes;")

In [16]:
# Fíjate que solo cambiamos lo que está dentro de DRIVER={...}
parametros = urllib.parse.quote_plus(f"DRIVER={{ODBC Driver 17 for SQL Server}};SERVER={server};DATABASE={database};Trusted_Connection=yes;")

In [17]:
import urllib
from sqlalchemy import create_engine

# 1. Credenciales y nombre de la tabla
server = 'DESKTOP-08BV2N8'
database = 'Betting_Project'
nombre_tabla_sql = 'Premier_Historico'

# 2. Creamos el Motor con tu Driver moderno (ODBC Driver 17)
parametros = urllib.parse.quote_plus(f"DRIVER={{ODBC Driver 17 for SQL Server}};SERVER={server};DATABASE={database};Trusted_Connection=yes;")
engine = create_engine(f"mssql+pyodbc:///?odbc_connect={parametros}")

# 3. La inyección masiva
print(f"⏳ Inyectando {df_final.shape[0]} partidos usando ODBC 17...")

df_final.to_sql(
    name=nombre_tabla_sql, 
    con=engine, 
    if_exists='append', 
    index=False         
)

print(f"✅ ¡Éxito total! Datos guardados en la tabla: {nombre_tabla_sql}")

⏳ Inyectando 380 partidos usando ODBC 17...
✅ ¡Éxito total! Datos guardados en la tabla: Premier_Historico